package com.example.a6times.data

import com.google.firebase.database.FirebaseDatabase
import kotlinx.coroutines.tasks.await


class UsersRepository{
    private val url = "https://six-times-228d1-default-rtdb.europe-west1.firebasedatabase.app/"
    private val database = FirebaseDatabase.getInstance(url)
                            .reference
                            .child("Users")

    suspend fun saveUser(user: Users) : Result<Unit> {
        val result = try {
            val newUserRef = database.push()
            val autoGeneratedId = newUserRef.key ?: throw Exception("ID oluşturulamadı")
            val userWithId = user.copy(userID = autoGeneratedId)

            newUserRef.setValue(userWithId).await()

            Result.success(Unit)

        }catch (e: Exception){
            Result.failure(e)
        }
        return result
    }
}